"""The starter set of plan templates.

The shapes that cover most of general practice, plus the ones each
specialty pack brings (`specialty` says which; a clinic gets a template
when it has that discipline enabled). They are a starting point,
not a doctrine: a clinic edits them, hides them, and — more usefully — saves
its own from any plan it has already built (``create_from_plan``).

Items are declared by catalog ``internal_code`` rather than by id, because a
template has to survive being seeded into a clinic whose catalog was created
independently. A code that is not in the clinic's catalog is skipped, and a
template whose items are all missing is not created at all: half a template
is worse than none, and the backfill script can fill it in later.

``phase`` is set only where the template disagrees with the catalog default.
"""

from typing import Final, TypedDict


class TemplateItemSpec(TypedDict, total=False):
    code: str
    phase: str | None


class TemplateSpec(TypedDict):
    key: str
    #: The discipline whose pack the template belongs to (catalog specialty key).
    specialty: str
    name: str
    description: str
    display_order: int
    items: list[TemplateItemSpec]


PLAN_TEMPLATES: Final[list[TemplateSpec]] = [
    {
        "key": "first_visit",
        "specialty": "general",
        "name": "Primera visita",
        "description": (
            "Consulta inicial con registro fotográfico y panorámica. "
            "No requiere seleccionar dientes."
        ),
        "display_order": 10,
        "items": [
            {"code": "DX-VISIT"},
            {"code": "DX-RXPAN"},
            {"code": "DX-PHOTO"},
        ],
    },
    {
        "key": "hygiene_phase",
        "specialty": "higiene",
        "name": "Fase higiénica",
        "description": (
            "Tartrectomía, instrucciones de higiene y revisión de control. "
            "No requiere seleccionar dientes."
        ),
        "display_order": 20,
        "items": [
            {"code": "PREV-CLEAN"},
            {"code": "PREV-HYGIENE-EDU"},
            {"code": "PREV-CHECKUP"},
        ],
    },
    {
        "key": "perio_basic",
        "specialty": "periodoncia",
        "name": "Tratamiento periodontal básico",
        "description": (
            "Estudio periodontal, raspado y alisado radicular por cuadrante y "
            "reevaluación. Selecciona un diente de cada cuadrante a tratar."
        ),
        "display_order": 30,
        "items": [
            {"code": "PERIO-STUDY"},
            {"code": "PERIO-RAR"},
            {"code": "PERIO-MAINT"},
        ],
    },
    {
        "key": "endo_resto_crown",
        "specialty": "endodoncia",
        "name": "Endodoncia + reconstrucción + corona",
        "description": (
            "La secuencia de tres pasos sobre la misma pieza. Selecciona el diente a tratar."
        ),
        "display_order": 40,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "ENDO-MULTI"},
            {"code": "REST-RECONSTR"},
            {"code": "REST-CROWN-POST-ENDO"},
        ],
    },
    {
        "key": "single_implant",
        "specialty": "implantologia",
        "name": "Implante unitario",
        "description": (
            "Extracción, implante, pilar y corona sobre implante. Selecciona la pieza a reponer."
        ),
        "display_order": 50,
        "items": [
            {"code": "DX-CBCT"},
            {"code": "SURG-EXT-SIMPLE", "phase": "estabilizacion"},
            {"code": "SURG-IMP-TI"},
            {"code": "REST-DEF-ABUT"},
            {"code": "REST-CROWN-IMPL-ZIR"},
        ],
    },
    {
        "key": "third_molars",
        "specialty": "cirugia",
        "name": "Extracción de cordales",
        "description": (
            "Extracción quirúrgica. Selecciona los cordales a extraer (18, 28, 38, 48)."
        ),
        "display_order": 60,
        "items": [
            {"code": "DX-RXPAN"},
            {"code": "SURG-EXT-3MOLAR"},
        ],
    },
    {
        "key": "orthodontics",
        "specialty": "ortodoncia",
        "name": "Ortodoncia",
        "description": ("Estudio, aparatología y retención. No requiere seleccionar dientes."),
        "display_order": 70,
        "items": [
            {"code": "DX-STUDY"},
            {"code": "DX-TELE"},
            {"code": "ORTO-METAL"},
            {"code": "ORTO-RET-REM"},
        ],
    },
    {
        "key": "aesthetics",
        "specialty": "estetica",
        "name": "Estética",
        "description": "Blanqueamiento y revisión de control. No requiere seleccionar dientes.",
        "display_order": 80,
        "items": [
            {"code": "EST-BLAN-CLIN"},
            {"code": "PREV-CHECKUP"},
        ],
    },
    {
        "key": "ortho_records",
        "specialty": "ortodoncia",
        "name": "Estudio de ortodoncia",
        "description": "Registros completos, cefalometría y presentación del plan. No requiere seleccionar dientes.",
        "display_order": 71,
        "items": [
            {"code": "ORTO-STUDY"},
            {"code": "ORTO-CEPH"},
            {"code": "ORTO-PLAN"},
        ],
    },
    {
        "key": "ortho_fixed",
        "specialty": "ortodoncia",
        "name": "Ortodoncia fija completa",
        "description": "Estudio, brackets, revisiones, retiro y retención fija y removible.",
        "display_order": 72,
        "items": [
            {"code": "ORTO-STUDY"},
            {"code": "ORTO-METAL"},
            {"code": "ORTO-REVIEW"},
            {"code": "ORTO-BRACK-DEBOND"},
            {"code": "ORTO-RET-FIX"},
            {"code": "ORTO-RET-ESSIX"},
        ],
    },
    {
        "key": "ortho_aligners",
        "specialty": "ortodoncia",
        "name": "Alineadores",
        "description": "Estudio, alineadores, ataches, stripping, refinamiento y retención.",
        "display_order": 73,
        "items": [
            {"code": "ORTO-STUDY"},
            {"code": "ORTO-INV-FULL"},
            {"code": "ORTO-ATTACH"},
            {"code": "ORTO-IPR"},
            {"code": "ORTO-ALIGN-REFINE"},
            {"code": "ORTO-RET-ESSIX"},
        ],
    },
    {
        "key": "ortho_interceptive",
        "specialty": "ortodoncia",
        "name": "Ortodoncia interceptiva",
        "description": "Primera fase en dentición mixta: estudio, expansión, aparatología y control de retención.",
        "display_order": 74,
        "items": [
            {"code": "ORTO-STUDY"},
            {"code": "ORTO-RPE"},
            {"code": "ORTO-INTERCEPT"},
            {"code": "ORTO-RET-REVIEW"},
        ],
    },
    {
        "key": "ortho_retention",
        "specialty": "ortodoncia",
        "name": "Retención",
        "description": "Retenedor fijo, retenedor termoformado y revisión de retención.",
        "display_order": 75,
        "items": [
            {"code": "ORTO-RET-FIX"},
            {"code": "ORTO-RET-ESSIX"},
            {"code": "ORTO-RET-REVIEW"},
        ],
    },
    {
        "key": "imaging_study",
        "specialty": "radiologia",
        "name": "Estudio de imagen",
        "description": "Panorámica, telerradiografía lateral e informe radiológico.",
        "display_order": 90,
        "items": [
            {"code": "DX-RXPAN"},
            {"code": "RX-CEPH-LAT"},
            {"code": "RX-REPORT"},
        ],
    },
    {
        "key": "lesion_biopsy",
        "specialty": "patologia_oral",
        "name": "Estudio de lesión oral",
        "description": "Consulta, biopsia, estudio histopatológico y seguimiento.",
        "display_order": 100,
        "items": [
            {"code": "PAT-CONS"},
            {"code": "PAT-BIOPSY-INC"},
            {"code": "PAT-HISTO"},
            {"code": "PAT-FOLLOW"},
        ],
    },
    {
        "key": "oral_medicine_first",
        "specialty": "medicina_oral",
        "name": "Primera consulta de medicina oral",
        "description": "Consulta, sialometría y revisión.",
        "display_order": 110,
        "items": [
            {"code": "MED-CONS"},
            {"code": "MED-SIALOMETRY"},
            {"code": "MED-FOLLOW"},
        ],
    },
    {
        "key": "tmd_splint",
        "specialty": "dolor_orofacial",
        "name": "Dolor orofacial con férula",
        "description": "Consulta, exploración de ATM, férula de estabilización, ajuste y revisión.",
        "display_order": 120,
        "items": [
            {"code": "DOF-CONS"},
            {"code": "DOF-EXAM"},
            {"code": "DOF-SPLINT-STAB"},
            {"code": "DOF-SPLINT-ADJ"},
            {"code": "DOF-FOLLOW"},
        ],
    },
    {
        "key": "sleep_mad",
        "specialty": "odontologia_sueno",
        "name": "Apnea del sueño con dispositivo de avance",
        "description": "Consulta, cribado, dispositivo de avance mandibular, titulación y revisión.",
        "display_order": 130,
        "items": [
            {"code": "SLEEP-CONS"},
            {"code": "SLEEP-SCREEN"},
            {"code": "SLEEP-MAD"},
            {"code": "SLEEP-MAD-TITR"},
            {"code": "SLEEP-FOLLOW"},
        ],
    },
    {
        "key": "lab_diagnostic",
        "specialty": "protesis_laboratorio",
        "name": "Estudio protésico de laboratorio",
        "description": "Modelos de estudio, montaje en articulador y encerado diagnóstico.",
        "display_order": 140,
        "items": [
            {"code": "LAB-STUDY-MODEL"},
            {"code": "LAB-ARTIC"},
            {"code": "LAB-WAXUP"},
        ],
    },
    {
        "key": "geriatric_care",
        "specialty": "odontogeriatria",
        "name": "Atención geriátrica",
        "description": "Valoración integral, higiene de prótesis, barniz de flúor e instrucción a cuidadores.",
        "display_order": 150,
        "items": [
            {"code": "GER-ASSESS"},
            {"code": "GER-DENTURE-HYG"},
            {"code": "GER-FLUOR"},
            {"code": "GER-CAREGIVER"},
            {"code": "GER-FOLLOW"},
        ],
    },
    {
        "key": "general_study",
        "specialty": "general",
        "name": "Estudio integral",
        "description": "Primera visita con panorámica, fotografías, riesgo de caries y presentación del plan.",
        "display_order": 11,
        "items": [
            {"code": "DX-VISIT"},
            {"code": "DX-RXPAN"},
            {"code": "DX-PHOTO"},
            {"code": "DX-CARIES-RISK"},
            {"code": "DX-PLAN"},
        ],
    },
    {
        "key": "general_checkup",
        "specialty": "general",
        "name": "Revisión y limpieza",
        "description": "Revisión periódica con limpieza y fluorización. No requiere seleccionar dientes.",
        "display_order": 12,
        "items": [
            {"code": "DX-REVIEW"},
            {"code": "PREV-CLEAN"},
            {"code": "PREV-FLUOR"},
        ],
    },
    {
        "key": "emergency_visit",
        "specialty": "general",
        "name": "Urgencia dental",
        "description": "Visita de urgencia, radiografía y tratamiento paliativo del dolor. Selecciona el diente.",
        "display_order": 13,
        "items": [
            {"code": "DX-URGENT"},
            {"code": "DX-RXPA"},
            {"code": "GEN-PAIN"},
        ],
    },
    {
        "key": "caries_treatment",
        "specialty": "general",
        "name": "Tratamiento de caries",
        "description": "Radiografía, obturación y revisión. Selecciona los dientes y sus superficies.",
        "display_order": 14,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "REST-COMP"},
            {"code": "DX-REVIEW"},
        ],
    },
    {
        "key": "dental_trauma",
        "specialty": "general",
        "name": "Traumatismo dental",
        "description": "Urgencia, radiografía, ferulización, pruebas de vitalidad y control.",
        "display_order": 15,
        "items": [
            {"code": "DX-URGENT"},
            {"code": "DX-RXPA"},
            {"code": "GEN-TRAUMA-SPLINT"},
            {"code": "ENDO-VITAL"},
            {"code": "DX-REVIEW"},
        ],
    },
    {
        "key": "bruxism_splint",
        "specialty": "general",
        "name": "Férula de descarga",
        "description": "Análisis oclusal, férula de descarga y ajuste.",
        "display_order": 16,
        "items": [
            {"code": "REST-OCC-ANALYSIS"},
            {"code": "REST-SPLINT-OCC"},
            {"code": "REST-SPLINT-OCC-ADJ"},
        ],
    },
    {
        "key": "hygiene_biofilm",
        "specialty": "higiene",
        "name": "Profilaxis con biofilm guiado",
        "description": "Índice de placa, terapia de biofilm guiada y enseñanza de higiene interdental.",
        "display_order": 21,
        "items": [
            {"code": "HYG-PLAQUE-INDEX"},
            {"code": "HYG-GBT"},
            {"code": "HYG-INTERDENTAL"},
        ],
    },
    {
        "key": "caries_prevention",
        "specialty": "higiene",
        "name": "Prevención de caries",
        "description": "Test salival, barniz de flúor, selladores y consejo dietético. Selecciona los dientes a sellar.",
        "display_order": 22,
        "items": [
            {"code": "HYG-SALIVA"},
            {"code": "HYG-FLUOR-VARNISH"},
            {"code": "PREV-SEAL"},
            {"code": "HYG-DIET"},
        ],
    },
    {
        "key": "dentine_sensitivity",
        "specialty": "higiene",
        "name": "Hipersensibilidad dentinaria",
        "description": "Tratamiento desensibilizante, terapia remineralizante e instrucciones de higiene.",
        "display_order": 23,
        "items": [
            {"code": "HYG-DESENS"},
            {"code": "HYG-REMIN"},
            {"code": "PREV-HYGIENE-EDU"},
        ],
    },
    {
        "key": "hygiene_ortho",
        "specialty": "higiene",
        "name": "Higiene en paciente con ortodoncia",
        "description": "Profilaxis adaptada, barniz de flúor e higiene interdental.",
        "display_order": 24,
        "items": [
            {"code": "HYG-ORTHO-CLEAN"},
            {"code": "HYG-FLUOR-VARNISH"},
            {"code": "HYG-INTERDENTAL"},
        ],
    },
    {
        "key": "perio_gingivitis",
        "specialty": "periodoncia",
        "name": "Gingivitis",
        "description": "Estudio periodontal, tratamiento de gingivitis, instrucciones de higiene y reevaluación.",
        "display_order": 31,
        "items": [
            {"code": "PERIO-STUDY"},
            {"code": "PERIO-GINGIVITIS"},
            {"code": "PREV-HYGIENE-EDU"},
            {"code": "PERIO-REEVAL"},
        ],
    },
    {
        "key": "perio_full_mouth",
        "specialty": "periodoncia",
        "name": "Periodontitis: desinfección de boca completa",
        "description": "Consulta, estudio, desinfección de boca completa, reevaluación y mantenimiento.",
        "display_order": 32,
        "items": [
            {"code": "PERIO-CONS"},
            {"code": "PERIO-STUDY"},
            {"code": "PERIO-RAR-FULL"},
            {"code": "PERIO-REEVAL"},
            {"code": "PERIO-MAINT"},
        ],
    },
    {
        "key": "perio_access_surgery",
        "specialty": "periodoncia",
        "name": "Cirugía periodontal de acceso",
        "description": "Estudio, colgajo de acceso, revisión posquirúrgica y mantenimiento. Selecciona los dientes del sector.",
        "display_order": 33,
        "items": [
            {"code": "PERIO-STUDY"},
            {"code": "PERIO-FLAP"},
            {"code": "PERIO-FOLLOW"},
            {"code": "PERIO-MAINT"},
        ],
    },
    {
        "key": "perio_regeneration",
        "specialty": "periodoncia",
        "name": "Regeneración periodontal",
        "description": "Radiografía, regeneración con membrana e injerto óseo, revisión y reevaluación. Selecciona el diente.",
        "display_order": 34,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "PERIO-GTR"},
            {"code": "PERIO-BONE-GRAFT"},
            {"code": "PERIO-FOLLOW"},
            {"code": "PERIO-REEVAL"},
        ],
    },
    {
        "key": "root_coverage",
        "specialty": "periodoncia",
        "name": "Recubrimiento radicular",
        "description": "Consulta, colgajo de avance coronal con injerto de tejido conectivo y revisión. Selecciona el diente.",
        "display_order": 35,
        "items": [
            {"code": "PERIO-CONS"},
            {"code": "PERIO-COVER"},
            {"code": "SURG-CONN-GRAFT"},
            {"code": "PERIO-FOLLOW"},
        ],
    },
    {
        "key": "crown_lengthening",
        "specialty": "periodoncia",
        "name": "Alargamiento coronario",
        "description": "Radiografía, alargamiento coronario y revisión. Selecciona el diente.",
        "display_order": 36,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "SURG-CROWN-LENGTH"},
            {"code": "PERIO-FOLLOW"},
        ],
    },
    {
        "key": "perio_maintenance",
        "specialty": "periodoncia",
        "name": "Mantenimiento periodontal",
        "description": "Reevaluación, mantenimiento e instrucciones de higiene.",
        "display_order": 37,
        "items": [
            {"code": "PERIO-REEVAL"},
            {"code": "PERIO-MAINT"},
            {"code": "PREV-HYGIENE-EDU"},
        ],
    },
    {
        "key": "periimplantitis",
        "specialty": "periodoncia",
        "name": "Periimplantitis",
        "description": "Radiografía, tratamiento de mucositis y de periimplantitis, y revisión. Selecciona el implante.",
        "display_order": 38,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "PERIO-MUCOSITIS"},
            {"code": "SURG-PERIIMP"},
            {"code": "PERIO-FOLLOW"},
        ],
    },
    {
        "key": "endo_single",
        "specialty": "endodoncia",
        "name": "Endodoncia unirradicular",
        "description": "Pruebas de vitalidad, radiografía, endodoncia, reconstrucción y control. Selecciona el diente.",
        "display_order": 41,
        "items": [
            {"code": "ENDO-VITAL"},
            {"code": "DX-RXPA"},
            {"code": "ENDO-UNI"},
            {"code": "REST-RECONSTR"},
            {"code": "ENDO-FOLLOW"},
        ],
    },
    {
        "key": "endo_emergency",
        "specialty": "endodoncia",
        "name": "Urgencia endodóncica",
        "description": "Pruebas de vitalidad, radiografía, apertura cameral y medicación intraconducto. Selecciona el diente.",
        "display_order": 42,
        "items": [
            {"code": "ENDO-VITAL"},
            {"code": "DX-RXPA"},
            {"code": "ENDO-URGENT"},
            {"code": "ENDO-MED-REFRESH"},
        ],
    },
    {
        "key": "endo_retreatment",
        "specialty": "endodoncia",
        "name": "Retratamiento endodóncico",
        "description": "Radiografía, retirada de perno, retratamiento, perno de fibra y control. Selecciona el diente.",
        "display_order": 43,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "ENDO-POST-REMOVE"},
            {"code": "ENDO-RETREAT-MULTI"},
            {"code": "ENDO-POST-FIBER"},
            {"code": "ENDO-FOLLOW"},
        ],
    },
    {
        "key": "endo_post_crown",
        "specialty": "endodoncia",
        "name": "Endodoncia + perno + corona",
        "description": "Endodoncia molar, perno de fibra, reconstrucción de muñón y corona. Selecciona el diente.",
        "display_order": 44,
        "items": [
            {"code": "ENDO-MULTI"},
            {"code": "ENDO-POST-FIBER"},
            {"code": "REST-CORE"},
            {"code": "REST-CROWN-POST-ENDO"},
        ],
    },
    {
        "key": "vital_pulp_therapy",
        "specialty": "endodoncia",
        "name": "Terapia pulpar vital",
        "description": "Pruebas de vitalidad, pulpotomía con biocerámico, reconstrucción y control. Selecciona el diente.",
        "display_order": 45,
        "items": [
            {"code": "ENDO-VITAL"},
            {"code": "ENDO-PULPOTOMY-FULL"},
            {"code": "REST-RECONSTR"},
            {"code": "ENDO-FOLLOW"},
        ],
    },
    {
        "key": "apical_microsurgery",
        "specialty": "endodoncia",
        "name": "Microcirugía apical",
        "description": "CBCT, microcirugía apical, retirada de sutura y control. Selecciona el diente.",
        "display_order": 46,
        "items": [
            {"code": "DX-CBCT"},
            {"code": "ENDO-MICROSURG"},
            {"code": "SURG-SUTURE-REMOVE"},
            {"code": "ENDO-FOLLOW"},
        ],
    },
    {
        "key": "immature_apex",
        "specialty": "endodoncia",
        "name": "Diente con ápice inmaduro",
        "description": "Radiografía, revascularización pulpar y control. Selecciona el diente.",
        "display_order": 47,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "ENDO-REVASC"},
            {"code": "ENDO-FOLLOW"},
        ],
    },
    {
        "key": "internal_bleaching",
        "specialty": "endodoncia",
        "name": "Blanqueamiento interno",
        "description": "Radiografía, blanqueamiento interno y reconstrucción. Selecciona el diente.",
        "display_order": 48,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "ENDO-BLEACH-INT"},
            {"code": "REST-RECONSTR"},
        ],
    },
    {
        "key": "implant_immediate",
        "specialty": "implantologia",
        "name": "Implante inmediato postextracción",
        "description": "Consulta, CBCT, extracción, implante inmediato, provisional, pilar y corona. Selecciona la pieza.",
        "display_order": 51,
        "items": [
            {"code": "IMP-CONS"},
            {"code": "DX-CBCT"},
            {"code": "SURG-EXT-SIMPLE", "phase": "estabilizacion"},
            {"code": "IMP-IMMEDIATE"},
            {"code": "REST-CROWN-IMPL-PROV"},
            {"code": "REST-DEF-ABUT"},
            {"code": "REST-CROWN-IMPL-ZIR"},
        ],
    },
    {
        "key": "implant_sinus_lift",
        "specialty": "implantologia",
        "name": "Implante con elevación de seno",
        "description": "Consulta, CBCT, planificación, elevación de seno, implante, segunda fase, pilar y corona.",
        "display_order": 52,
        "items": [
            {"code": "IMP-CONS"},
            {"code": "DX-CBCT"},
            {"code": "IMP-PLAN"},
            {"code": "SURG-SINUS"},
            {"code": "SURG-IMP-TI"},
            {"code": "IMP-2ND-STAGE"},
            {"code": "REST-DEF-ABUT"},
            {"code": "REST-CROWN-IMPL-ZIR"},
        ],
    },
    {
        "key": "implant_bone_regen",
        "specialty": "implantologia",
        "name": "Regeneración ósea e implante diferido",
        "description": "CBCT, aumento óseo con membrana, implante, pilar de cicatrización y corona.",
        "display_order": 53,
        "items": [
            {"code": "DX-CBCT"},
            {"code": "SURG-BONE-HORIZ"},
            {"code": "IMP-MEMBRANE"},
            {"code": "SURG-IMP-TI"},
            {"code": "REST-HEAL-ABUT"},
            {"code": "REST-CROWN-IMPL-ZIR"},
        ],
    },
    {
        "key": "implant_bridge",
        "specialty": "implantologia",
        "name": "Puente sobre implantes",
        "description": "CBCT, planificación, implantes, pilares y puente. Selecciona las piezas a reponer.",
        "display_order": 54,
        "items": [
            {"code": "DX-CBCT"},
            {"code": "IMP-PLAN"},
            {"code": "SURG-IMP-TI"},
            {"code": "REST-DEF-ABUT"},
            {"code": "IMP-BRIDGE"},
        ],
    },
    {
        "key": "implant_overdenture",
        "specialty": "implantologia",
        "name": "Sobredentadura sobre implantes",
        "description": "CBCT, planificación, implantes, ataches y sobredentadura.",
        "display_order": 55,
        "items": [
            {"code": "DX-CBCT"},
            {"code": "IMP-PLAN"},
            {"code": "SURG-IMP-TI"},
            {"code": "IMP-LOCATOR"},
            {"code": "PROT-OVERDENT"},
        ],
    },
    {
        "key": "implant_full_arch",
        "specialty": "implantologia",
        "name": "Arcada completa fija sobre implantes",
        "description": "Consulta, CBCT, planificación, cirugía guiada, provisional de carga inmediata, prótesis definitiva y mantenimiento.",
        "display_order": 56,
        "items": [
            {"code": "IMP-CONS"},
            {"code": "DX-CBCT"},
            {"code": "IMP-PLAN"},
            {"code": "IMP-GUIDE"},
            {"code": "IMP-PROV-ARCH"},
            {"code": "IMP-ALLON4"},
            {"code": "IMP-MAINT"},
        ],
    },
    {
        "key": "socket_preservation",
        "specialty": "implantologia",
        "name": "Extracción con preservación alveolar",
        "description": "Extracción, preservación alveolar y retirada de sutura. Selecciona la pieza.",
        "display_order": 57,
        "items": [
            {"code": "SURG-EXT-SIMPLE", "phase": "estabilizacion"},
            {"code": "SURG-ALV-PRESERV"},
            {"code": "SURG-SUTURE-REMOVE"},
        ],
    },
    {
        "key": "implant_maintenance",
        "specialty": "implantologia",
        "name": "Mantenimiento de implantes",
        "description": "Revisión, radiografía de control y mantenimiento.",
        "display_order": 58,
        "items": [
            {"code": "IMP-FOLLOW"},
            {"code": "DX-RXPA"},
            {"code": "IMP-MAINT"},
        ],
    },
    {
        "key": "simple_extraction",
        "specialty": "cirugia",
        "name": "Extracción",
        "description": "Radiografía, extracción y revisión. Selecciona el diente.",
        "display_order": 61,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "SURG-EXT-SIMPLE"},
            {"code": "SURG-FOLLOW"},
        ],
    },
    {
        "key": "impacted_third_molar",
        "specialty": "cirugia",
        "name": "Cordal impactado",
        "description": "Consulta, CBCT, extracción quirúrgica, retirada de sutura y revisión. Selecciona el cordal.",
        "display_order": 62,
        "items": [
            {"code": "SURG-CONS"},
            {"code": "DX-CBCT"},
            {"code": "SURG-EXT-3M-IMPACT"},
            {"code": "SURG-SUTURE-REMOVE"},
            {"code": "SURG-FOLLOW"},
        ],
    },
    {
        "key": "odontogenic_infection",
        "specialty": "cirugia",
        "name": "Infección odontogénica",
        "description": "Urgencia, radiografía, drenaje y revisión. Selecciona el diente.",
        "display_order": 63,
        "items": [
            {"code": "DX-URGENT"},
            {"code": "DX-RXPA"},
            {"code": "SURG-DRAIN"},
            {"code": "SURG-FOLLOW"},
        ],
    },
    {
        "key": "impacted_canine",
        "specialty": "cirugia",
        "name": "Diente retenido: fenestración",
        "description": "CBCT, fenestración, retirada de sutura y revisión. Selecciona el diente.",
        "display_order": 64,
        "items": [
            {"code": "DX-CBCT"},
            {"code": "SURG-EXPOSE"},
            {"code": "SURG-SUTURE-REMOVE"},
            {"code": "SURG-FOLLOW"},
        ],
    },
    {
        "key": "frenectomy",
        "specialty": "cirugia",
        "name": "Frenectomía",
        "description": "Consulta, frenectomía y retirada de sutura.",
        "display_order": 65,
        "items": [
            {"code": "SURG-CONS"},
            {"code": "SURG-FREN"},
            {"code": "SURG-SUTURE-REMOVE"},
        ],
    },
    {
        "key": "jaw_cyst_surgery",
        "specialty": "cirugia",
        "name": "Quiste de los maxilares",
        "description": "CBCT, exéresis del quiste, biopsia, retirada de sutura y revisión.",
        "display_order": 66,
        "items": [
            {"code": "DX-CBCT"},
            {"code": "SURG-CYST"},
            {"code": "SURG-BIOPSY"},
            {"code": "SURG-SUTURE-REMOVE"},
            {"code": "SURG-FOLLOW"},
        ],
    },
    {
        "key": "preprosthetic_surgery",
        "specialty": "cirugia",
        "name": "Cirugía preprotésica",
        "description": "Panorámica, extracciones múltiples, alveoloplastia y retirada de sutura.",
        "display_order": 67,
        "items": [
            {"code": "DX-RXPAN"},
            {"code": "SURG-EXT-MULTI"},
            {"code": "SURG-ALVEOLOPL"},
            {"code": "SURG-SUTURE-REMOVE"},
        ],
    },
    {
        "key": "orthognathic_surgery",
        "specialty": "cirugia",
        "name": "Cirugía ortognática",
        "description": "Consulta, estudio, valoración preanestésica, planificación virtual, cirugía y revisión.",
        "display_order": 68,
        "items": [
            {"code": "MXF-CONS-01"},
            {"code": "MXF-EST-01"},
            {"code": "MXF-PREAN-01"},
            {"code": "MXF-VSP-01"},
            {"code": "MXF-CIR-01"},
            {"code": "MXF-FOLLOW"},
        ],
    },
    {
        "key": "smile_design_veneers",
        "specialty": "estetica",
        "name": "Diseño de sonrisa con carillas",
        "description": "Consulta, diseño digital, mock-up, provisionales y carillas de porcelana. Selecciona los dientes.",
        "display_order": 81,
        "items": [
            {"code": "EST-CONS"},
            {"code": "EST-DSD"},
            {"code": "EST-MOCKUP"},
            {"code": "EST-VEN-PROV"},
            {"code": "REST-VEN-PORC"},
        ],
    },
    {
        "key": "composite_veneers",
        "specialty": "estetica",
        "name": "Carillas de composite",
        "description": "Consulta, toma de color y carillas de composite. Selecciona los dientes.",
        "display_order": 82,
        "items": [
            {"code": "EST-CONS"},
            {"code": "EST-SHADE"},
            {"code": "REST-VEN-COMP"},
        ],
    },
    {
        "key": "whitening_combined",
        "specialty": "estetica",
        "name": "Blanqueamiento combinado",
        "description": "Limpieza, toma de color, blanqueamiento combinado, desensibilizante y mantenimiento.",
        "display_order": 83,
        "items": [
            {"code": "PREV-CLEAN"},
            {"code": "EST-SHADE"},
            {"code": "EST-BLAN-COMBO"},
            {"code": "EST-BLAN-DESENS"},
            {"code": "EST-BLAN-MAINT"},
        ],
    },
    {
        "key": "white_spots",
        "specialty": "estetica",
        "name": "Manchas blancas",
        "description": "Microabrasión, infiltración de resina y remineralización. Selecciona los dientes.",
        "display_order": 84,
        "items": [
            {"code": "EST-MICROAB"},
            {"code": "EST-INFILT"},
            {"code": "EST-REMIN"},
        ],
    },
    {
        "key": "diastema_closure",
        "specialty": "estetica",
        "name": "Cierre de diastemas",
        "description": "Consulta, mock-up, cierre con composite y contorneado. Selecciona los dientes.",
        "display_order": 85,
        "items": [
            {"code": "EST-CONS"},
            {"code": "EST-MOCKUP"},
            {"code": "EST-DIASTEMA"},
            {"code": "EST-CONTOUR"},
        ],
    },
    {
        "key": "gingival_aesthetics",
        "specialty": "estetica",
        "name": "Estética gingival",
        "description": "Consulta, diseño digital de sonrisa y recontorneado gingival. Selecciona los dientes.",
        "display_order": 86,
        "items": [
            {"code": "EST-CONS"},
            {"code": "EST-DSD"},
            {"code": "EST-GUM-LASER"},
        ],
    },
    {
        "key": "imaging_ortho_records",
        "specialty": "radiologia",
        "name": "Registros de imagen para ortodoncia",
        "description": "Panorámica, telerradiografía, serie fotográfica, escaneado y cefalometría digital.",
        "display_order": 91,
        "items": [
            {"code": "DX-RXPAN"},
            {"code": "RX-CEPH-LAT"},
            {"code": "RX-PHOTO-SET"},
            {"code": "RX-SCAN"},
            {"code": "RX-CEPH-DIGITAL"},
        ],
    },
    {
        "key": "imaging_implants",
        "specialty": "radiologia",
        "name": "Estudio de imagen para implantes",
        "description": "CBCT con planificación, escaneado intraoral, superposición e informe.",
        "display_order": 92,
        "items": [
            {"code": "RX-CBCT-IMPL"},
            {"code": "RX-SCAN"},
            {"code": "RX-SUPERIMP"},
            {"code": "RX-REPORT-CBCT"},
        ],
    },
    {
        "key": "imaging_caries",
        "specialty": "radiologia",
        "name": "Estudio radiográfico de caries",
        "description": "Serie de aletas de mordida, periapical e informe.",
        "display_order": 93,
        "items": [
            {"code": "RX-BW-SERIES"},
            {"code": "DX-RXPA"},
            {"code": "RX-REPORT"},
        ],
    },
    {
        "key": "imaging_full_series",
        "specialty": "radiologia",
        "name": "Serie radiográfica completa",
        "description": "Serie periapical completa, aletas de mordida e informe.",
        "display_order": 94,
        "items": [
            {"code": "RX-SERIES"},
            {"code": "RX-BW-SERIES"},
            {"code": "RX-REPORT"},
        ],
    },
    {
        "key": "imaging_tmj",
        "specialty": "radiologia",
        "name": "Estudio de imagen de ATM",
        "description": "Panorámica, CBCT de ATM e informe.",
        "display_order": 95,
        "items": [
            {"code": "DX-RXPAN"},
            {"code": "RX-CBCT-ATM"},
            {"code": "RX-REPORT-CBCT"},
        ],
    },
    {
        "key": "imaging_airway",
        "specialty": "radiologia",
        "name": "Estudio de imagen de vía aérea",
        "description": "Telerradiografía lateral, CBCT de vía aérea e informe.",
        "display_order": 96,
        "items": [
            {"code": "RX-CEPH-LAT"},
            {"code": "RX-CBCT-AIRWAY"},
            {"code": "RX-REPORT-CBCT"},
        ],
    },
    {
        "key": "oral_cancer_screening",
        "specialty": "patologia_oral",
        "name": "Cribado de cáncer oral",
        "description": "Consulta, cribado, autofluorescencia y mapeo fotográfico.",
        "display_order": 101,
        "items": [
            {"code": "PAT-CONS"},
            {"code": "PAT-SCREEN"},
            {"code": "PAT-AUTOFLUOR"},
            {"code": "PAT-PHOTO-MAP"},
        ],
    },
    {
        "key": "benign_lesion_excision",
        "specialty": "patologia_oral",
        "name": "Exéresis de lesión benigna",
        "description": "Consulta, exéresis, estudio histopatológico y seguimiento.",
        "display_order": 102,
        "items": [
            {"code": "PAT-CONS"},
            {"code": "PAT-EXC-BENIGN"},
            {"code": "PAT-HISTO"},
            {"code": "PAT-FOLLOW"},
        ],
    },
    {
        "key": "mucocele_excision",
        "specialty": "patologia_oral",
        "name": "Mucocele",
        "description": "Consulta, exéresis, estudio histopatológico y seguimiento.",
        "display_order": 103,
        "items": [
            {"code": "PAT-CONS"},
            {"code": "PAT-MUCOCELE"},
            {"code": "PAT-HISTO"},
            {"code": "PAT-FOLLOW"},
        ],
    },
    {
        "key": "jaw_cyst_pathology",
        "specialty": "patologia_oral",
        "name": "Quiste: enucleación y estudio",
        "description": "Consulta, CBCT, enucleación, estudio histopatológico y seguimiento.",
        "display_order": 104,
        "items": [
            {"code": "PAT-CONS"},
            {"code": "DX-CBCT"},
            {"code": "PAT-CYST-ENUC"},
            {"code": "PAT-HISTO"},
            {"code": "PAT-FOLLOW"},
        ],
    },
    {
        "key": "premalignant_lesion",
        "specialty": "patologia_oral",
        "name": "Lesión potencialmente maligna",
        "description": "Consulta, mapeo fotográfico, biopsia, estudio histopatológico y control periódico.",
        "display_order": 105,
        "items": [
            {"code": "PAT-CONS"},
            {"code": "PAT-PHOTO-MAP"},
            {"code": "PAT-BIOPSY-INC"},
            {"code": "PAT-HISTO"},
            {"code": "PAT-PMD-FOLLOW"},
        ],
    },
    {
        "key": "dry_mouth",
        "specialty": "medicina_oral",
        "name": "Boca seca",
        "description": "Consulta, sialometría, manejo de xerostomía, pauta de sustitutos salivales y revisión.",
        "display_order": 111,
        "items": [
            {"code": "MED-CONS"},
            {"code": "MED-SIALOMETRY"},
            {"code": "MED-XEROST"},
            {"code": "MED-SALIVA-STIM"},
            {"code": "MED-FOLLOW"},
        ],
    },
    {
        "key": "oral_lichen",
        "specialty": "medicina_oral",
        "name": "Liquen plano oral",
        "description": "Consulta, analítica, control del liquen y revisión.",
        "display_order": 112,
        "items": [
            {"code": "MED-CONS"},
            {"code": "MED-BLOOD"},
            {"code": "MED-LICHEN"},
            {"code": "MED-FOLLOW"},
        ],
    },
    {
        "key": "burning_mouth",
        "specialty": "medicina_oral",
        "name": "Síndrome de boca ardiente",
        "description": "Consulta, analítica, sialometría, manejo y revisión.",
        "display_order": 113,
        "items": [
            {"code": "MED-CONS"},
            {"code": "MED-BLOOD"},
            {"code": "MED-SIALOMETRY"},
            {"code": "MED-BMS"},
            {"code": "MED-FOLLOW"},
        ],
    },
    {
        "key": "oral_candidiasis",
        "specialty": "medicina_oral",
        "name": "Candidiasis oral",
        "description": "Consulta, tratamiento y revisión.",
        "display_order": 114,
        "items": [
            {"code": "MED-CONS"},
            {"code": "MED-CANDIDA"},
            {"code": "MED-FOLLOW"},
        ],
    },
    {
        "key": "oncology_patient",
        "specialty": "medicina_oral",
        "name": "Paciente oncológico",
        "description": "Valoración previa, panorámica, manejo de mucositis, fotobiomodulación y seguimiento.",
        "display_order": 115,
        "items": [
            {"code": "MED-PREONC"},
            {"code": "DX-RXPAN"},
            {"code": "MED-MUCOSITIS"},
            {"code": "MED-LASER"},
            {"code": "MED-POSTONC"},
        ],
    },
    {
        "key": "antiresorptive_patient",
        "specialty": "medicina_oral",
        "name": "Paciente con antirresortivos",
        "description": "Valoración previa, panorámica, informe para el médico tratante y revisión.",
        "display_order": 116,
        "items": [
            {"code": "MED-BISPHOS"},
            {"code": "DX-RXPAN"},
            {"code": "MED-REPORT"},
            {"code": "MED-FOLLOW"},
        ],
    },
    {
        "key": "compromised_patient",
        "specialty": "medicina_oral",
        "name": "Paciente médicamente comprometido",
        "description": "Valoración, interconsulta, pauta de profilaxis antibiótica e informe.",
        "display_order": 117,
        "items": [
            {"code": "MED-COMPROMISED"},
            {"code": "MED-INTERCONS"},
            {"code": "MED-PROPHYL"},
            {"code": "MED-REPORT"},
        ],
    },
    {
        "key": "tmd_conservative",
        "specialty": "dolor_orofacial",
        "name": "Trastorno temporomandibular: manejo conservador",
        "description": "Consulta, exploración, autocuidado, ejercicios, fisioterapia y revisión.",
        "display_order": 121,
        "items": [
            {"code": "DOF-CONS"},
            {"code": "DOF-EXAM"},
            {"code": "DOF-EDU"},
            {"code": "DOF-EXERCISE"},
            {"code": "DOF-PHYSIO"},
            {"code": "DOF-FOLLOW"},
        ],
    },
    {
        "key": "myofascial_pain",
        "specialty": "dolor_orofacial",
        "name": "Dolor miofascial",
        "description": "Consulta, exploración, infiltración de puntos gatillo, punción seca, ejercicios y revisión.",
        "display_order": 122,
        "items": [
            {"code": "DOF-CONS"},
            {"code": "DOF-EXAM"},
            {"code": "DOF-TRIGGER"},
            {"code": "DOF-DRY-NEEDLE"},
            {"code": "DOF-EXERCISE"},
            {"code": "DOF-FOLLOW"},
        ],
    },
    {
        "key": "tmj_arthrocentesis",
        "specialty": "dolor_orofacial",
        "name": "Artrocentesis de ATM",
        "description": "Consulta, imagen de ATM, artrocentesis, ácido hialurónico y revisión.",
        "display_order": 123,
        "items": [
            {"code": "DOF-CONS"},
            {"code": "DOF-IMAGING"},
            {"code": "DOF-ARTHRO"},
            {"code": "DOF-HA-ATM"},
            {"code": "DOF-FOLLOW"},
        ],
    },
    {
        "key": "bruxism_management",
        "specialty": "dolor_orofacial",
        "name": "Bruxismo",
        "description": "Valoración, férula de estabilización, ajuste, control de hábitos y revisión de férula.",
        "display_order": 124,
        "items": [
            {"code": "DOF-BRUX"},
            {"code": "DOF-SPLINT-STAB"},
            {"code": "DOF-SPLINT-ADJ"},
            {"code": "DOF-SLEEP-HYG"},
            {"code": "DOF-SPLINT-REVIEW"},
        ],
    },
    {
        "key": "bruxism_botulinum",
        "specialty": "dolor_orofacial",
        "name": "Bruxismo con toxina botulínica",
        "description": "Valoración, toxina botulínica en maseteros y revisión.",
        "display_order": 125,
        "items": [
            {"code": "DOF-BRUX"},
            {"code": "DOF-BOTOX"},
            {"code": "DOF-FOLLOW"},
        ],
    },
    {
        "key": "neuropathic_pain",
        "specialty": "dolor_orofacial",
        "name": "Dolor neuropático",
        "description": "Consulta, valoración, bloqueo diagnóstico, pauta farmacológica y revisión.",
        "display_order": 126,
        "items": [
            {"code": "DOF-CONS"},
            {"code": "DOF-NEURO"},
            {"code": "DOF-BLOCK-DX"},
            {"code": "DOF-PHARMA"},
            {"code": "DOF-FOLLOW"},
        ],
    },
    {
        "key": "sleep_diagnosis",
        "specialty": "odontologia_sueno",
        "name": "Estudio de ronquido y apnea",
        "description": "Consulta, cribado, exploración de vía aérea, poligrafía domiciliaria e informe para la unidad de sueño.",
        "display_order": 131,
        "items": [
            {"code": "SLEEP-CONS"},
            {"code": "SLEEP-SCREEN"},
            {"code": "SLEEP-EXAM"},
            {"code": "SLEEP-HST"},
            {"code": "SLEEP-REFERRAL"},
        ],
    },
    {
        "key": "sleep_mad_digital",
        "specialty": "odontologia_sueno",
        "name": "Dispositivo de avance digital con control",
        "description": "Consulta, registro de mordida, dispositivo digital, titulación, poligrafía de control y revisión.",
        "display_order": 132,
        "items": [
            {"code": "SLEEP-CONS"},
            {"code": "SLEEP-BITE-REG"},
            {"code": "SLEEP-MAD-DIGITAL"},
            {"code": "SLEEP-MAD-TITR"},
            {"code": "SLEEP-EFFICACY"},
            {"code": "SLEEP-FOLLOW"},
        ],
    },
    {
        "key": "sleep_appliance_follow",
        "specialty": "odontologia_sueno",
        "name": "Seguimiento del dispositivo de avance",
        "description": "Revisión, manejo de efectos secundarios y reposicionador matutino.",
        "display_order": 133,
        "items": [
            {"code": "SLEEP-FOLLOW"},
            {"code": "SLEEP-SIDE"},
            {"code": "SLEEP-MORNING"},
        ],
    },
    {
        "key": "sleep_child",
        "specialty": "odontologia_sueno",
        "name": "Respiración oral y ronquido infantil",
        "description": "Valoración, terapia miofuncional, expansión maxilar y derivación a otorrinolaringología.",
        "display_order": 134,
        "items": [
            {"code": "SLEEP-PED"},
            {"code": "SLEEP-MYO"},
            {"code": "SLEEP-EXPANSION"},
            {"code": "SLEEP-ENT-REF"},
        ],
    },
    {
        "key": "lab_crown",
        "specialty": "protesis_laboratorio",
        "name": "Corona de laboratorio",
        "description": "Escaneado, toma de color, provisional fresado y corona de zirconio. Selecciona el diente.",
        "display_order": 141,
        "items": [
            {"code": "LAB-SCAN-MODEL"},
            {"code": "LAB-SHADE"},
            {"code": "LAB-PROV-PMMA"},
            {"code": "LAB-CROWN-ZIR"},
        ],
    },
    {
        "key": "lab_complete_denture",
        "specialty": "protesis_laboratorio",
        "name": "Prótesis completa de laboratorio",
        "description": "Cubeta individual, placa base y rodillos, montaje en articulador, prueba de dientes y prótesis.",
        "display_order": 142,
        "items": [
            {"code": "LAB-TRAY"},
            {"code": "LAB-BASE-RIMS"},
            {"code": "LAB-ARTIC"},
            {"code": "LAB-SETUP"},
            {"code": "LAB-FULL"},
        ],
    },
    {
        "key": "lab_partial_denture",
        "specialty": "protesis_laboratorio",
        "name": "Prótesis esquelética de laboratorio",
        "description": "Modelos de estudio, cubeta individual, estructura esquelética y prueba de dientes.",
        "display_order": 143,
        "items": [
            {"code": "LAB-STUDY-MODEL"},
            {"code": "LAB-TRAY"},
            {"code": "LAB-PART-METAL"},
            {"code": "LAB-SETUP"},
        ],
    },
    {
        "key": "lab_implant_crown",
        "specialty": "protesis_laboratorio",
        "name": "Corona sobre implante de laboratorio",
        "description": "Modelo con encía artificial, llave de verificación, pilar personalizado y corona. Selecciona la pieza.",
        "display_order": 144,
        "items": [
            {"code": "LAB-SOFT-TISSUE"},
            {"code": "LAB-JIG"},
            {"code": "LAB-IMPL-ABUT"},
            {"code": "LAB-IMPL-CROWN"},
        ],
    },
    {
        "key": "lab_smile_design",
        "specialty": "protesis_laboratorio",
        "name": "Diseño de sonrisa de laboratorio",
        "description": "Diseño digital, encerado digital, mock-up y carillas cerámicas. Selecciona los dientes.",
        "display_order": 145,
        "items": [
            {"code": "LAB-SMILE-DESIGN"},
            {"code": "LAB-DIGITAL-WAX"},
            {"code": "LAB-MOCKUP"},
            {"code": "LAB-VENEER"},
        ],
    },
    {
        "key": "lab_splint",
        "specialty": "protesis_laboratorio",
        "name": "Férula de descarga de laboratorio",
        "description": "Escaneado, registro de mordida y férula de descarga.",
        "display_order": 146,
        "items": [
            {"code": "LAB-SCAN-MODEL"},
            {"code": "LAB-BITE-REG"},
            {"code": "LAB-SPLINT-MICH"},
        ],
    },
    {
        "key": "geriatric_home_care",
        "specialty": "odontogeriatria",
        "name": "Atención a domicilio",
        "description": "Visita a domicilio, valoración integral, profilaxis adaptada, instrucción a cuidadores y plan de cuidados.",
        "display_order": 151,
        "items": [
            {"code": "GER-HOME"},
            {"code": "GER-ASSESS"},
            {"code": "GER-CLEAN"},
            {"code": "GER-CAREGIVER"},
            {"code": "GER-CARE-PLAN"},
        ],
    },
    {
        "key": "geriatric_dry_mouth",
        "specialty": "odontogeriatria",
        "name": "Boca seca en el mayor",
        "description": "Revisión de medicación, manejo de boca seca, barniz de flúor y revisión.",
        "display_order": 152,
        "items": [
            {"code": "GER-POLYPHARM"},
            {"code": "GER-XEROST"},
            {"code": "GER-FLUOR"},
            {"code": "GER-FOLLOW"},
        ],
    },
    {
        "key": "root_caries",
        "specialty": "odontogeriatria",
        "name": "Caries radicular",
        "description": "Valoración, restauración, fluoruro diamino de plata, barniz de flúor y revisión.",
        "display_order": 153,
        "items": [
            {"code": "GER-ASSESS"},
            {"code": "GER-ROOT-CARIES"},
            {"code": "GER-SDF"},
            {"code": "GER-FLUOR"},
            {"code": "GER-FOLLOW"},
        ],
    },
    {
        "key": "denture_care",
        "specialty": "odontogeriatria",
        "name": "Cuidado de prótesis",
        "description": "Higiene de prótesis, tratamiento de úlcera por decúbito, ajuste, rebase e instrucción de adhesivo.",
        "display_order": 154,
        "items": [
            {"code": "GER-DENTURE-HYG"},
            {"code": "GER-SORE"},
            {"code": "GER-DENTURE-ADJ"},
            {"code": "GER-RELINE"},
            {"code": "GER-ADHESIVE"},
        ],
    },
    {
        "key": "denture_stomatitis",
        "specialty": "odontogeriatria",
        "name": "Estomatitis protésica",
        "description": "Tratamiento, higiene de prótesis, instrucción a cuidadores y revisión.",
        "display_order": 155,
        "items": [
            {"code": "GER-STOMATITIS"},
            {"code": "GER-DENTURE-HYG"},
            {"code": "GER-CAREGIVER"},
            {"code": "GER-FOLLOW"},
        ],
    },
    {
        "key": "palliative_oral_care",
        "specialty": "odontogeriatria",
        "name": "Cuidados orales paliativos",
        "description": "Plan de cuidados, cuidados paliativos, coordinación con la familia e instrucción a cuidadores.",
        "display_order": 156,
        "items": [
            {"code": "GER-CARE-PLAN"},
            {"code": "GER-PALLIATIVE"},
            {"code": "GER-FAMILY"},
            {"code": "GER-CAREGIVER"},
        ],
    },
    {
        "key": "ped_first_visit",
        "specialty": "odontopediatria",
        "name": "Primera visita infantil",
        "description": "Primera visita, riesgo de caries, educación en higiene y fluorización.",
        "display_order": 161,
        "items": [
            {"code": "PED-FIRST"},
            {"code": "PED-CARIES-RISK"},
            {"code": "PED-HYG-EDU"},
            {"code": "PED-FLUOR"},
        ],
    },
    {
        "key": "ped_baby_visit",
        "specialty": "odontopediatria",
        "name": "Consulta del bebé",
        "description": "Consulta del bebé, consejo sobre hábitos y asesoramiento dietético.",
        "display_order": 162,
        "items": [
            {"code": "PED-BABY"},
            {"code": "PED-HABIT-COUNSEL"},
            {"code": "PED-DIET"},
        ],
    },
    {
        "key": "ped_prevention",
        "specialty": "odontopediatria",
        "name": "Prevención infantil",
        "description": "Profilaxis, fluorización, selladores, consejo dietético y revisión. Selecciona los molares a sellar.",
        "display_order": 163,
        "items": [
            {"code": "PREV-CLEAN-PED"},
            {"code": "PED-FLUOR"},
            {"code": "PED-SEAL"},
            {"code": "PED-DIET"},
            {"code": "PED-REVIEW"},
        ],
    },
    {
        "key": "ped_caries",
        "specialty": "odontopediatria",
        "name": "Caries en dentición temporal",
        "description": "Sesión de adaptación, obturación, fluorización y revisión. Selecciona los dientes.",
        "display_order": 164,
        "items": [
            {"code": "PED-ADAPT"},
            {"code": "PED-FILL-TEMP"},
            {"code": "PED-FLUOR"},
            {"code": "PED-REVIEW"},
        ],
    },
    {
        "key": "ped_pulpotomy_crown",
        "specialty": "odontopediatria",
        "name": "Pulpotomía y corona",
        "description": "Pulpotomía, corona preformada y revisión. Selecciona el diente.",
        "display_order": 165,
        "items": [
            {"code": "PED-PULPOTOMY"},
            {"code": "PED-CROWN-SS"},
            {"code": "PED-REVIEW"},
        ],
    },
    {
        "key": "ped_space_maintainer",
        "specialty": "odontopediatria",
        "name": "Extracción y mantenedor de espacio",
        "description": "Extracción de la pieza temporal, mantenedor banda-ansa y revisión. Selecciona el diente.",
        "display_order": 166,
        "items": [
            {"code": "PED-EXT-TEMP"},
            {"code": "PED-SPACE-BAND"},
            {"code": "PED-REVIEW"},
        ],
    },
    {
        "key": "ped_trauma",
        "specialty": "odontopediatria",
        "name": "Traumatismo dental infantil",
        "description": "Valoración, radiografía, ferulización, reconstrucción y control.",
        "display_order": 167,
        "items": [
            {"code": "PED-TRAUMA-EXAM"},
            {"code": "DX-RXPA"},
            {"code": "PED-TRAUMA-SPLINT"},
            {"code": "PED-TRAUMA-RESTORE"},
            {"code": "PED-TRAUMA-FOLLOW"},
        ],
    },
    {
        "key": "ped_mih",
        "specialty": "odontopediatria",
        "name": "Hipomineralización incisivo-molar",
        "description": "Riesgo de caries, tratamiento de MIH, fluorización, selladores y revisión. Selecciona los dientes.",
        "display_order": 168,
        "items": [
            {"code": "PED-CARIES-RISK"},
            {"code": "PED-MIH"},
            {"code": "PED-FLUOR"},
            {"code": "PED-SEAL"},
            {"code": "PED-REVIEW"},
        ],
    },
    {
        "key": "ped_sedation",
        "specialty": "odontopediatria",
        "name": "Tratamiento infantil bajo sedación",
        "description": "Manejo de conducta, sedación consciente, obturación y revisión.",
        "display_order": 169,
        "items": [
            {"code": "PED-BEHAV"},
            {"code": "GEN-SED-N2O"},
            {"code": "PED-FILL-TEMP"},
            {"code": "PED-REVIEW"},
        ],
    },
    {
        "key": "single_crown",
        "specialty": "rehabilitacion",
        "name": "Corona unitaria",
        "description": "Radiografía, reconstrucción de muñón, provisional y corona de zirconio. Selecciona el diente.",
        "display_order": 171,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "REST-CORE"},
            {"code": "REST-CROWN-PROV"},
            {"code": "REST-CROWN-ZIR"},
        ],
    },
    {
        "key": "fixed_bridge",
        "specialty": "rehabilitacion",
        "name": "Puente fijo",
        "description": "Radiografía, puente provisional y puente de zirconio. Selecciona pilares y pónticos.",
        "display_order": 172,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "REST-BRIDGE-PROV"},
            {"code": "REST-BRIDGE-ZIR"},
        ],
    },
    {
        "key": "inlay_onlay",
        "specialty": "rehabilitacion",
        "name": "Incrustación",
        "description": "Radiografía, incrustación provisional y overlay cerámico. Selecciona el diente.",
        "display_order": 173,
        "items": [
            {"code": "DX-RXPA"},
            {"code": "REST-INLAY-PROV"},
            {"code": "REST-OVER-CER"},
        ],
    },
    {
        "key": "partial_denture",
        "specialty": "rehabilitacion",
        "name": "Prótesis parcial removible",
        "description": "Consulta, panorámica, prótesis esquelética, ajuste y revisión.",
        "display_order": 174,
        "items": [
            {"code": "REHAB-CONS"},
            {"code": "DX-RXPAN"},
            {"code": "PROT-PART-METAL"},
            {"code": "PROT-ADJ"},
            {"code": "PROT-REVIEW"},
        ],
    },
    {
        "key": "complete_dentures",
        "specialty": "rehabilitacion",
        "name": "Prótesis completa",
        "description": "Consulta, registro de dimensión vertical, prótesis superior e inferior, ajuste y revisión.",
        "display_order": 175,
        "items": [
            {"code": "REHAB-CONS"},
            {"code": "REHAB-VDO"},
            {"code": "PROT-FULL-PAIR"},
            {"code": "PROT-ADJ"},
            {"code": "PROT-REVIEW"},
        ],
    },
    {
        "key": "immediate_denture",
        "specialty": "rehabilitacion",
        "name": "Prótesis inmediata",
        "description": "Panorámica, alveoloplastia, prótesis inmediata, rebase blando y rebase definitivo.",
        "display_order": 176,
        "items": [
            {"code": "DX-RXPAN"},
            {"code": "SURG-ALVEOLOPL"},
            {"code": "PROT-FULL-IMMED"},
            {"code": "PROT-RELINE-SOFT"},
            {"code": "PROT-RELINE-CHAIR"},
        ],
    },
    {
        "key": "full_mouth_rehab",
        "specialty": "rehabilitacion",
        "name": "Rehabilitación oral completa",
        "description": "Consulta, planificación, arco facial, dimensión vertical, desprogramador, rehabilitación y ajuste oclusal.",
        "display_order": 177,
        "items": [
            {"code": "REHAB-CONS"},
            {"code": "REHAB-PLAN"},
            {"code": "REHAB-FACEBOW"},
            {"code": "REHAB-VDO"},
            {"code": "REHAB-DEPROG"},
            {"code": "REST-FMR"},
            {"code": "PROT-OCC-ADJ"},
        ],
    },
    {
        "key": "prosthesis_maintenance",
        "specialty": "rehabilitacion",
        "name": "Mantenimiento de prótesis",
        "description": "Revisión, rebasado y ajuste oclusal.",
        "display_order": 178,
        "items": [
            {"code": "PROT-REVIEW"},
            {"code": "PROT-REBASE"},
            {"code": "PROT-OCC-ADJ"},
        ],
    },
]
